# Page settings

baseurl = "/"
languageCode = "en-us"
title = "Teofil Nakov "
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = ""
    author = "Teofil Nakov"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Teofil Nakov"
        tagline = "R/Shiny developer | Data Scientist | Bioinformatician "
        avatar = "teo-web.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        #icon = "fa-envelope"
        url = "mailto: teofiln@gmail.com"
        title = "teofiln@gmail.com"
        
        [[params.contact.list]]
        class = "github"
        #icon = "fa-github"
        url = "//github.com/teofiln"
        title = "GitHub"

        [[params.contact.list]]
        class = "linkedin"
        #icon = "fa-twitter"
        url = "//https://www.linkedin.com/in/teofil-nakov-ph-d-874a04202/"
        title = "LinkedIn"

        [[params.contact.list]]
        class = "website"
        #icon = "ai-google-scholar"
        url = "//scholar.google.com/citations?user=2lKX40AAAAAJ&hl=en"
        title = "Google Scholar"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "PhD in Plant Biology"
        college = "University of Texas at Austin"
        dates = "2014"

        [[params.education.list]]
        degree = "BSc in Biochemistry and Physiology"
        college = "Sts Cyril & Methodius University Skopje"
        dates = "2005"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Macedonian"
        level = "Native"
        
        [[params.language.list]]
        language = "English"
        level = "Fluent"

        [[params.language.list]]
        language = "Spanish"
        level = "Conversational"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Football (with the feet)"

        [[params.interests.list]]
        interest = "Chess (Liches rapid rating 1800)"

        [[params.interests.list]]
        interest = "Baking (pizza, bread)"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "About"
        summary = "Researcher, software developer, and bioinformatician with a PhD in Plant biology from UT Austin and 6+ year of postdoctoral research experience. Programming in R for 12+ years and Shiny 8+ years. Advanced, independent, and rapid developer of Shiny applications, leveraging the Golem or Rhino framework and experienced in developing custom user interfaces and complex server logic. Flexible and adaptable. Welcoming steep learning curves with reasonable time frames." 
        
    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-archive"
        title = "Experience"
        
        [[params.jobs.list]]
        position = "R/Shiny developer"
        dates = "2020 - "
        company = "Independent consultant or part-time employee"
        details = "Developed custom R/Shiny solutions for over 20 clients primarily on Upwork."
        
        [[params.jobs.list]]
        position = "Postdoctoral fellow"
        dates = "2014 - 2020"
        company = "University of Arkansas Fayetteville, Arkansas, USA"
        details = "Research on diatom diversification, transcriptional response to salinity, local adaptation to salinity gradients, phylogenomics and genome evolution."

        [[params.jobs.list]]
        position = "Research/Teaching assistant"
        dates = "< 2014"
        company = "The University of Texas at Austin, Texas, USA and Sts Cyril & Methodius University Skopje, Macedonia"
        details = "Taught: Genetics, Limnology, Phycology. Field work: Ohrid, Prespa, Iowa, Guam, Malili lakes (Sulawesi), Baikal (Siberia)."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-flask"
        title = "Open source projects "
        
        [[params.projects.list]]
        title = "{r2lambda} (lead)"
        url = "https://github.com/discindo/r2lambda"
        tagline = "R package to get started and become productive with AWS Lambda from R"
        
        [[params.projects.list]]
        title = "{newscatcheR} (contributor)"
        url = "https://github.com/discindo/newscatcheR"
        tagline = "Programmatically collect normalized news from (almost) any website using `R`"
        
        [[params.projects.list]]
        title = "{tinselR} (contributor)"
        url = "https://github.com/jennahamlin/tinselR"
        tagline = "Graphical viewer of Newick-formatted phylogenetic trees and as an application for producing publication-ready figures"
        
        [[params.projects.list]]
        title = "Reproducible research guide (in Macedonian) (lead)"
        url = "https://github.com/discindo/booklet"
        tagline = "A guide for best practices in reproducible data analysis. Available: https://discindo.github.io/booklet/"
        
        [[params.projects.list]]
        title = "{phynotate} (lead)"
        url = "https://github.com/teofiln/phynotate"
        tagline = "A low(ish)-level `R` library for creating customizible `{shiny}` applications to visualize, customize, and annotate phylogenetic trees."

        [[params.projects.list]]
        title = "{gghisse} (lead)"
        url = "https://github.com/discindo/gghisse"
        tagline = "An `R` package and `{shiny}` application for post-processing results from species diversification modelling with [`{hisse}`](https://cran.r-project.org/web/packages/hisse/index.html)."

    # Projects section
    [params.past]
        enable = true
        icon = "fa-flask"
        title = "Past research projects"
        
        [[params.future.list]]
        title = "Functional traits, life history, and diversification"
        url = ""
        tagline = "A collection of studies ranging from the [ecology of primary chloroplast endosymbiosis](https://www.pnas.org/content/114/50/E10606.abstract) to [global phytoplankton diversity patterns](https://www.nature.com/articles/s41396-018-0221-y). I've also studied the evolution od diatom [cell size](https://aslopubs.onlinelibrary.wiley.com/doi/abs/10.4319/lo.2014.59.1.0079), [growth forms](https://www.nature.com/articles/ismej2014108), and [development](https://www.sciencedirect.com/science/article/pii/S1055790316301798) and diversification from a [life history](https://nph.onlinelibrary.wiley.com/doi/full/10.1111/nph.15137) and [ecological](https://www.biorxiv.org/content/10.1101/406165v1.abstract) perspectives."

        [[params.future.list]]
        title = "Phylogenomics and genome evolution"
        url = ""
        tagline = "An ongoing project investigating [historical polyploidy](https://bsapubs.onlinelibrary.wiley.com/doi/full/10.1002/ajb2.1056) and [genome evolution](https://link.springer.com/article/10.1007/s00294-016-0652-9) in diatoms using whole [genome and transcriptome](https://diatom.shinyapps.io/TranscribedDiatoms/) scale data."

        [[params.future.list]]
        title = "Acclimation and adaptation to changing salinity"
        url = ""
        tagline = "One aspect of this project is on the relationships between [growth reaction norms at different salinities](https://diatom.shinyapps.io/Diatoms_and_Salinity/) and gene expression, while another uses whole-genome resequencing to understand local adaptation in the [Baltic Sea salinity gradient](https://diatom.shinyapps.io/baltic-sea-gradient-maps/)."

    # Skills section
    [params.skills]
        enable = false
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python & Django"
        level = "98%"
                
        [[params.skills.list]]
        skill = "Javascript & jQuery"
        level = "98%"

        [[params.skills.list]]
        skill = "Angular"
        level = "95%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "95%"

        [[params.skills.list]]
        skill = "Ruby on Rails"
        level = "75%"

        [[params.skills.list]]
        skill = "Sketch & Photoshop"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Teofil Nakov"
